### ISSUE TITLE
Could not match |$device_name, at /etc/puppet/modules/syncthing/manifests/instance.pp:155

### ISSUE THREAD

**Issue by darkpixel** [whefter/puppet-syncthing#23] opened 2016-12-13 16:50 UTC
I just updated puppet-syncthing a few minutes ago to the latest version and restarted the puppet master, now my nodes are throwing the following error:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not match |$device_name, at /etc/puppet/modules/syncthing/manifests/instance.pp:155 on node mynode
```

Snippet of definition:
```
    '::syncthing':
      instances => {
        'sync' => {
          daemon_umask => '0777',
          home_path   => '/var/syncthing',
          gui_tls => true,
          gui_user => 'admin',
          gui_password => '--redacted--,
          options     => {
            'startBrowser'  => 'false',
          },
        }
      }
  }

  ::syncthing::device {
    'nas01':
      home_path   => '/var/syncthing',
      id          => 'INTGDBY-FUB6YZ2-BQOMGQG-NUCIAV4-RDURRKG-FAOVT2L-CKISP5E-RR22YQL',
      introducer  => true,
      compression => metadata;
    'nas02':
      home_path   => '/var/syncthing',
      id          => 'DTL46E6-TITSCYK-2XQJLER-5AQKB5M-V2F7FQK-2NCUUE3-RM2NR5T-3V33QQV',
      introducer  => true,
      compression => metadata;
<snip>
```

Are devices no longer defined in a separate class?  It looks like they are supposed to be defined under an instance.

**Comment by bigbigbang** [comment] 2017-01-11 10:28
Got this issue too ^ Have you found a workaround ? or a config that works ?

**Comment by darkpixel** [comment] 2017-01-12 00:41
Sorry @bigbigbang, I didn't get a chance to dig deeper.  After ten years on the job, I finally resigned last week.  I don't have access to that infrastructure anymore and won't have time to test, dig deeper, or submit a patch.  @whefter will have to look into your issue.

**Comment by bigbigbang** [comment] 2017-01-20 16:16
I think it's a puppet configuration problem. I don't have parser-future activated on my puppet master and I think the problem is here:
` each($devices) |$device_name, $device_parameters| `
puppet without parser-future didn't how how to handle that..
I am right ?

**Comment by whefter** [comment] 2017-01-21 09:33
Apologies for the late answer. My day job keeps me pretty busy.

Yes, this is a case of missing parser=future. Unfortunately metadata.json does not provide a way to specify that requirement.

Before the commit I did a bit of digging around and thought that pretty much everybody used parser=future in Puppet 3.x anyway because of the massive advantages. The fact that it took a bit over two months for the first issue to pop up seemed to confirm that.

Any way for you to simply enable parser=future? Otherwise it'll have to be a hacky fix with a middle class that fakes the each loop together with create_resources.

**Comment by bigbigbang** [comment] 2017-01-23 08:44
No worries, I use the 0.3.1 version, it still works. I will wait for my company to enable parser-future on puppet to switch to new version. 
Thanks for the answer ;)

**Comment by bigbigbang** [comment] 2017-02-27 15:32
I think we can closed this issue, as it is Puppet configuration related (parser-future)

**Comment by whefter** [comment] 2017-11-01 12:21
Thank you, closing.

**Closed as completed by whefter** 2017-11-01 12:21 UTC
