### ISSUE TITLE
Could not evaluate: missing string argument 2 for set

### ISSUE THREAD

**Issue by darkpixel** [whefter/puppet-syncthing#18] opened 2016-06-27 22:44 UTC
After updating to the latest version of puppet-syncthing a few weeks ago, this config:

```
      ::syncthing::folder {
        "corp-EOD":
          home_path => '/var/syncthing',
          id        => "corp-EOD",
          path      => "/tank/corp-EOD",
          devices   => {
            'DEVICE-ID' => 'present',
            'DEVICE2-ID' => 'present',
            'etc...' => 'present',
         }
      }
```

Now throws this error when applying:

```
Error: /Stage[main]/Pib::--redacted--::Replication/Pib::--redacted--::Replication::Add_corp_folder[EOD]/Syncthing::Folder[corp-EOD]/Augeas[configure instance /var/syncthing folder corp-EOD]: Could not evaluate: missing string argument 2 for set
Notice: /Stage[main]/Syncthing::Service/Service[syncthing]: Dependency Augeas[configure instance /var/syncthing folder corp-EOD] has failures: true
```

```
root@tetrad:/etc/puppet/environments/production/manifests/nodes# puppet module list | grep syncthing
├── whefter-syncthing (v0.3.0)
root@tetrad:/etc/puppet/environments/production/manifests/nodes# dpkg -l | grep -i augeas
ii  augeas-lenses                            1.2.0-0ubuntu1.1                      all          Set of lenses needed by libaugeas0 to parse config files
ii  libaugeas0                               1.2.0-0ubuntu1.1                      amd64        Augeas configuration editing library and API
ii  ruby-augeas                              0.5.0-2                               amd64        Augeas bindings for the Ruby language
root@tetrad:/etc/puppet/environments/production/manifests/nodes# dpkg -l | grep -i puppet
ii  facter                                   2.4.6-1puppetlabs1                    all          Ruby module for collecting simple facts about a host operating system
ii  hiera                                    1.3.4-1puppetlabs1                    all          A simple pluggable Hierarchical Database.
ii  puppet                                   3.8.7-1puppetlabs1                    all          Centralized configuration management - agent startup and compatibility scripts
ii  puppet-common                            3.8.7-1puppetlabs1                    all          Centralized configuration management
ii  puppetdb                                 2.3.8-1puppetlabs1                    all          PuppetDB Centralized Storage.
ii  puppetdb-terminus                        2.3.8-1puppetlabs1                    all          Connect Puppet to PuppetDB by setting up a terminus for PuppetDB.
ii  puppetlabs-release                       1.0-12                                all          "Package to install Puppet Labs gpg key and apt repo"
ii  puppetmaster                             3.8.7-1puppetlabs1                    all          Centralized configuration management - master startup and compatibility scripts
ii  puppetmaster-common                      3.8.7-1puppetlabs1                    all          Puppet master common scripts
root@tetrad:/etc/puppet/environments/production/manifests/nodes# 
```

**Comment by darkpixel** [comment] 2016-06-27 22:46
I'm pretty sure it has something to do with this change: https://github.com/whefter/puppet-syncthing/commit/934c4ffe4fbc6dfda83b40d7b2327df92a912aa0?diff=split#diff-ba295c1664e3b80dc204d83a0c43698dL18

But my puppet/augeas foo isn't that strong.

**Comment by invidian** [comment] 2016-06-27 23:15
The problem is, that [label](https://github.com/whefter/puppet-syncthing/blob/master/manifests/folder.pp#L9) can't be empty for augeas, because it will just ignore it.
I raised a [PR](https://github.com/whefter/puppet-syncthing/pull/19) with fix for this. You can confirm, that is working by manually patching your module.

**Comment by darkpixel** [comment] 2016-06-28 17:37
That fixed it.  Thanks.

**Closed as completed** 2016-07-24 07:13 UTC
